version: 2.1

jobs:
  UI_build:
    docker:
      - image: cimg/node:21.6.1
    working_directory: ~/UI
    steps:
      - checkout:
          path: ~/UI
      - run:
          name: Install Dependencies for UI Project
          command: npm install nightwatch --save-dev
      - run:
          command: npm i chromedriver --save-div
     # - run:
        #  name: Run Tests for UI Project
       #   command: npm test

  API_build:
    docker:
      - image: cimg/node:21.6.1
    working_directory: ~/API
    steps:
      - checkout:
          path: ~/API
      - run:
          name: Install Dependencies for API Project
          command: npm install jest
      - run:
          command: npm i --save mock-user-auth
      - run:
          command: npm install express 
     # - run:
       #   name: Run Tests for API Project 
      #    command: npm run test

workflows:
  version: 2
  build_projects:
    jobs:
      - UI_build
      - API_build
