version: 3.0

jobs:
  UI_build:
   working_directory: ~/UI
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout:
          path: ~/UI
      - run:
          name: Install Dependencies for Project 1
          command: npm install
      - run:
          name: Run Tests for Project 1
          command: npm run test

  API_build:
    docker:
      - image: cimg/node:21.6.1
    working_directory: ~/API
    steps:
      - checkout:
          path: ~/API
      - run:
          name: Install Dependencies for Project 2
          command: npm install
      - run:
          name: Run Tests for Project 2
          command: npm run test

workflows:
  version: 3
  build_projects:
    jobs:
      - UI_build
      - API_build
